name: Deploy-test-Test PyPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Adoubt from 524-actiondemo
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      - name: Run tests with coverage
        run: |
          pytest --cov==survey_cleaner --cov-report=xml --cov-report=term --cov-branch

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          use_oidc: true
          fail_ci_if_error: false 
          verbose: true 

  style-check:
      runs-on: ubuntu-latest

      steps:
        - name: Check-out repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Install ruff for style checking
          run: pip install ruff
        - name: Run ruff style check
          run: ruff check src/

  build-deploy:

    needs: [unit-tests, style-check]
    runs-on: ubuntu-latest

    # Add a condition to only run deploy on push to main branch (merge to main)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-tags: true

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.12"

      - name: Install hatch
        run: |
            python -m pip install --upgrade pip
            python -m pip install hatch

      - name: Build package using Hatch
        run: |
            hatch build

            echo ""
            echo "Generated files:"
            ls -lh dist/

      # - name: Store the distribution packages
      #   uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4
      #   with:
      #     name: python-package-distributions
      #     path: dist/
      #     if-no-files-found: error

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          # Skip if there is an existing version on Test PyPI
          skip-existing: true

      - name: Test install from TestPyPI
        run: |
            pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple \
            survey_cleaner
