name: Deploy-test-Test PyPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Adoubt from 524-actiondemo
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check-out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      - name: Run tests with coverage
        run: |
          pytest --cov=survey_cleaner --cov-report=xml --cov-report=term --cov-branch

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage.xml
          use_oidc: true
          fail_ci_if_error: false 

  style-check:
      runs-on: ubuntu-latest

      steps:
        - name: Check-out repository
          uses: actions/checkout@v7

        - name: Set up Python
          uses: actions/setup-python@v7
          with:
            python-version: '3.12'

        - name: Install ruff for style checking
          run: pip install ruff
        - name: Run ruff style check
          run: ruff check src/

  release:
    name: Semantic Versioning
    runs-on: ubuntu-latest
    needs: [unit-tests, style-check]
    concurrency: release


    if: >
      github.event_name == 'push' && github.ref == 'refs/heads/main' &&
      !contains(github.event.head_commit.message, 'Automatically generated by python-semantic-release')
    
    permissions:
      id-token: write
      contents: write 

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: true
          push: true


  build-deploy:

    needs: [unit-tests, style-check, release]
    runs-on: ubuntu-latest

    # Add a condition to only run deploy on push to main branch (merge to main)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
        with:
          ref: main
          fetch-depth: 0
          fetch-tags: true

      - name: Pull latest changes
        run: git pull origin main

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"

      - name: Install hatch
        run: |
            python -m pip install --upgrade pip
            python -m pip install hatch

      - name: Build package using Hatch
        run: |
            hatch build

            echo ""
            echo "Generated files:"
            ls -lh dist/

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          # Skip if there is an existing version on Test PyPI
          skip-existing: true

      - name: Test install from TestPyPI
        run: |
            pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple \
            survey_cleaner
